### ISSUE TITLE
Beautify selection?

### ISSUE THREAD

**Issue by grimen** [mocoso/code-beautifier.tmbundle#2]
Not sure if this is "possible" (with more or less effort), but it would be useful.

**Comment by mocoso** [comment]
I can see that it would be useful. It would have to be approximate because the current implementation matches the end of blocks depending on how they were started, but I am sure some reasonable approximation could be made (where blocks that started before the selection were ended within the selection).

I do not intent to implement this feature but if someone else wanted to fork/patch the project they would be more than welcome.
